### ISSUE TITLE
error in setup

### ISSUE THREAD

**Issue by felluksch** [DanceJL/Dance.jl#2]
Hi,
thank you for the development of this package. I wanted to give it a shot, so I installed the package and executed the following commands in the Julia REPL:
```
cd("path/to/dir")
using Dance; start_project("dance-test")
```

Which throws an error:
```
ERROR: IOError: could not spawn `chmod -R 755 'C:\Users\Lenovo\Documents\code\dance-test'`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
 [2] #550 at .\process.jl:112 [inlined]
 [3] setup_stdios(::Base.var"#550#551"{Cmd}, ::Array{Any,1}) at .\process.jl:196
 [4] _spawn at .\process.jl:111 [inlined]
 [5] run(::Cmd; wait::Bool) at .\process.jl:439
 [6] run at .\process.jl:438 [inlined]
 [7] start_project(::String, ::String) at C:\Users\Lenovo\.julia\packages\Dance\VFdge\src\Dance.jl:69
 [8] start_project(::String) at C:\Users\Lenovo\.julia\packages\Dance\VFdge\src\Dance.jl:65
 [9] top-level scope at REPL[4]:1
```
All files (dance.jl, routes.jl, Global.jl, base.html, favicon.ico) seem to be generated though.

**Comment by yoh-meyers** [comment]
Hi,

Thanks for your interest in my package.

If I understand the files are generated under Windows OS, but you get above error.
I am developing under OSX and tests seem to work on TravisCI for Windows.

That said in code I use ```run(`chmod -R 755 $project_directory`)```, after Julia's inbuilt `chmod` function didn't fully work.
So aware that the command is not Windows compatible.

Are you able to continue with rest of process, i.e: run `julia dance.jl` to get webserver started?
Also are you able to edit code files of generated project folder?

**Comment by felluksch** [comment]
Okay, thanks, I won't worry about that then. I can start a server and everything works (almost) as expected. routes.jl and Global.jl (which I had to edit in order to run the hello world example) were read-only.

Some suggestions: You could provide a link to the sample app (which you shared in the Julia Discourse post) here as well. Also, it might be a good idea to include sample `dev.jl` and `prod.jl` files in the default setup generated by `start_project()` and `include("dev.jl")` by default so you can just hit `julia dance.jl` without further ado to run the hello world example.

**Comment by yoh-meyers** [comment]
Thanks for feedback!

Have noted that your files were in read-only mode.
So will keep this open till I find solution.

Will have to make better demo app in future, as more features are added.
But noted, thank you.

About `dev.jl`, there is a comment in `Global.jl`.
I prefer to leave it as such, as I do want the users to understand and remember that the `include("dev.jl")` has to be commented when releasing to production.
So bit of security check.

**Comment by yoh-meyers** [comment]
If you are reading this, do you happen to have suggestion how to run equivalent of `chmod` on a Windows system.

Thanks!

**Comment by yoh-meyers** [comment]
Windows read-only issue fixed with https://github.com/DanceJL/Dance.jl/commit/0046f6a5238514b74755ccc018f0514ce0e46556.

So please upgrade to v0.2.2
